// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGDVve1e93oXhlJWpNrbMQU-yl8fF4QPM',
    appId: '1:969708040312:web:1dd9d68984c75e98eb7d8d',
    messagingSenderId: '969708040312',
    projectId: 'one-space-33e71',
    authDomain: 'one-space-33e71.firebaseapp.com',
    storageBucket: 'one-space-33e71.appspot.com',
    measurementId: 'G-XDKQTEV6CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmBCPcYGzxobePgcsBx0_ZDWF33GFmbGI',
    appId: '1:969708040312:android:d7d3424d086d5442eb7d8d',
    messagingSenderId: '969708040312',
    projectId: 'one-space-33e71',
    storageBucket: 'one-space-33e71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcP6aiZsRspr87OKRLioxQzZxWjYVO6EU',
    appId: '1:969708040312:ios:0fb93b5833da8fa1eb7d8d',
    messagingSenderId: '969708040312',
    projectId: 'one-space-33e71',
    storageBucket: 'one-space-33e71.appspot.com',
    iosClientId: '969708040312-n5u6h7un2dhau6fadkqsjjl7slr8lhav.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneSpace',
  );
}
